### ISSUE TITLE
Update README to notify users of Godeps for dependencies

### ISSUE THREAD

**Issue by advanderveer** [redspread/spread#108]
The Current README suggest it is possible to just `go get` on non OSX systems, this won't work since dependencies will be retrieved without using Godeps.

**Comment by feliksik** [comment]
I ran into a dependencies problem doing `go get` on ubuntu, as the current spread `master` uses removed functionality from github.com/docker/docker :+1: 

`gopath/src/k8s.io/kubernetes/pkg/util/parsers/parsers.go:30: undefined: parsers.ParseRepositoryTag`

Checking out the docker repo with tag 1.6 fixed the problem. I'm not sure how the generic `go get` mechanism allows you to prevent this, but if it can't I suggest a documentation instruction on how to use glide/godeps/whatever to make the build reliable.

**Comment by ethernetdan** [comment]
Hmm... All deps are supposed to be included using native Go vendoring

Which version of Go are you using? And when you run `go env` is GO15VENDOREXPERIMENT set to 1?. It should get noted somewhere that for Go 1.5 it must be set in order for vendoring to work. The feature left experimental status in 1.6 and is now enabled by default.

**Comment by vsimon** [comment]
Just ran into this problem as well on linux. Using go 1.5.

`GO15VENDOREXPERIMENT=1 go get rsprd.com/spread/cmd/spread` fixes it.

**Comment by feliksik** [comment]
You guys are right. It was a configuration mistake (GO15VENDOREXPERIMENT=1). Discussed this with @advanderveer . 

The existence of the Godeps directory confused us. 

This issue can be closed.

**Comment by vsimon** [comment]
I think this was closed prematurely. 
I still think there should be some documentation on the README for either using Go 1.6 or using GO15VENDOREXPERIMENT=1 with Go 1.5 or something else regarding vendoring. Otherwise someone will run into this problem again and will have to sift through open and closed issues to find this thread to get around their build problem.
