### ISSUE TITLE
Enhance documentation

### ISSUE THREAD

**Issue by chaosaffe** [redspread/spread#118]
The documentation (especially for GitLab CI) is fairly sparse. It would be great if you guys could spend some time writing a description of what spread is and is not for, especially covering the advantages over just using the existing tools (i.e. Docker CLI and kubectl)

**Comment by ethernetdan** [comment]
Better documentation is in the works!

Definitely like the idea of providing examples of the different usecases for `spread` alongside `kubectl` and `docker`.

**Comment by thecanadianbaker** [comment]
I only ask for it because I don't quite understand where it fits in my
toolbelt. I look forward to the updates!

**Comment by scruplelesswizard** [comment]
Stale. Closing
