### ISSUE TITLE
Unrecognized import path "rsprd.com/spread/cmd/spread"

### ISSUE THREAD

**Issue by dalanmiller** [redspread/spread#119]
Following the redspread guide:

```sh
$ go get rsprd.com/spread/cmd/spread
package rsprd.com/spread/cmd/spread: unrecognized import path "rsprd.com/spread/cmd/spread" (https fetch: Get https://rsprd.com/spread/cmd/spread?go-get=1: dial tcp: lookup rsprd.com: no such host)
```

**Comment by ethernetdan** [comment]
Hmm... haven't seen that one before

What are the results when `curl -v https://rsprd.com/spread/cmd/spread\?go-get\=1` is run?

**Comment by dalanmiller** [comment]
Of course, now the `curl` request works fine, and then `go get` works as
well. Not sure what happened there.

**Comment by ethernetdan** [comment]
Of course :D

I'm going to close this issue but if you run into it again, feel free to reopen and we can troubleshoot.
