### ISSUE TITLE
Cannot update version throught `go get`

### ISSUE THREAD

**Issue by paurullan** [redspread/spread#127]
I am willing to try spread but cannot get the latest (0.1.4 at this moment) version. With both the `go get` command and the binary from the release I get a 0.0.3 snapshot.

```bash
$ go version
go version go1.5.1 linux/amd64
$ GO15VENDOREXPERIMENT=1 go get -u rsprd.com/spread/cmd/spread
$ ./spread --v
spread version 0.0.3
```

In fact, the release binary gives you the same version:
https://github.com/redspread/spread/releases/tag/0.1.4
https://github.com/redspread/spread/releases/download/0.1.4/spread_linux_amd64

I am trying to make the build this is another different issue.

**Comment by mfburnett** [comment]
Hey @paurullan - slightly embarrassing, that's actually the latest version, we just haven't gotten around to updating the version number it returns. 😅 So you're all good. Will update it this weekend.

**Comment by ethernetdan** [comment]
#121 will resolve this
