### ISSUE TITLE
kubectl client 1.2.0 seems to have an issue with spread 0.0.3

### ISSUE THREAD

**Issue by brandon-bethke-neudesic** [redspread/spread#128]
When I update kubectl client to 1.2.0, the command seems to stop working. Specifically, what happens for me is when I run the** kubectl get pods** command, nothing is returned. When I am using kubectl client 1.1.7, I get the expected result.

**Comment by ethernetdan** [comment]
Having some trouble recreating this one with kubectl 1.2.0

Could you post the output of `kubectl cluster-info`?

**Comment by brandon-bethke-neudesic** [comment]
Sorry ignore this. I can no longer reproduce the issue either.
