### ISSUE TITLE
Support google-json-key for authentication through Gitlab CI

### ISSUE THREAD

**Issue by roelvanhintum** [redspread/spread#133]
Is support for google-json-key files missing? I've created a service account, but i can't figure out how to use the json file for authentication through Gitlab. Kubectl has the following to allow this:

```
--google-json-key="": The Google Cloud Platform Service Account JSON Key to use for authentication.
```

**Comment by mfburnett** [comment]
hey @roelvanhintum, sorry for the delayed response on this - we're looking into your issue over the next few days and will get back to you asap!
