### ISSUE TITLE
Managing secrets

### ISSUE THREAD

**Issue by onbjerg** [redspread/spread#154]
How is Spread going to handle secrets? Comitting them to version control in plain text is less than ideal.

How about some sort of easy way to manage keys for encrypting the secrets (maybe using Keybase)?

Some commands that might reflect what I'm thinking:

```
spread secrets add [file] - Encrypts the file using the public keys managed by Spread and adds it to version control
spread secrets rm [file] - Decrypts the file and removes it from version control
spread keys add [key ID or keybase username] - Adds the key to use for encryption and re-encrypts secret files
spread keys rm [key ID or keybase username] - Removes the key and re-encrypts the secret files
```

Keybase could be a solution. Encrypting via. the keybase CLI is pretty easy, especially for multiple users, and public keys are pulled from their servers after the users identity has been verified. This _would_ add another dependency, though.

Thoughts?

**Comment by mfburnett** [comment]
hey @onbjerg, sorry for the delayed response - secret management is definitely something we've thought about, including the encryption ideas you proposed. we wanted to avoid (as much as possible) actual storage of the encrypted information, though we haven't come up with a solution we like yet. after our next release, we're going to definitely focus on solving this problem, and would love your input - will let you know as soon as we start working on it!

btw, have you seen this issue? what do you think about this proposed solution? https://github.com/kubernetes/kubernetes/issues/10439

**Comment by onbjerg** [comment]
Hi @mfburnett. Thanks for the response. Looking forward to hearing progress on this, and I agree that it might not be the best solution.

I've seen kubernetes/kubernetes#10439 but there doesn't seem to be much progress on it. I haven't really read up on it in a while, so I might do that tomorrow when I have the time.
