### ISSUE TITLE
Replace pods associated with RCs that have been modified

### ISSUE THREAD

**Issue by ethernetdan** [redspread/spread#60]
If any part of a ReplicationControllers PodTemplateSpec gets modified we should either do a rolling replace or simply delete its pods.

**Comment by ethernetdan** [comment]
There's an important distinction in usecases between developing and deploying here.

**Developing**
likely want pods to be deleted immediately in the interest of prototyping

**Deploying**
need a much more sophisticated deployment strategy

We've talked about adding a new command `spread build` (or similar) which would have a focus on iteration. @mfburnett thoughts on priorities here?

**Comment by mfburnett** [comment]
Why delete pods immediately? I'd imagine the trigger to delete pods would still be the same (a command) between `spread deploy` and `spread build`

**Comment by ethernetdan** [comment]
To enable rapid iteration, I'm thinking for `build` that pod deletion can be disabled with a flag but by default they're deleted. I would like to be able to make changes to config/image run a single command and test them.

I am playing around with the idea of creating a differentiation between working locally and working with arbitrary remote clusters. There would be a set of commands including `spread build` that would be designed for use while iterating and affect the local cluster only.
