### ISSUE TITLE
Error when deploying `kube-mattermost` on Kube 1.2 alpha

### ISSUE THREAD

**Issue by kern** [redspread/spread#67]
I'm running Kubernetes 1.2 alpha 8. I was able to install `spread` successfully via the instructions on the README, but when deploying I get an error:

```
~/D/kube-mattermost (master) $ spread deploy .
Deploying 3 objects using the default context.
Did not deploy.: could not get 'default/mattermost-app' (Service): export of "services" is not supported
```

**Comment by mfburnett** [comment]
Thanks @kern. @ethernetdan and I will look into this over the next few days. I'll get back to you when we start looking at it!

**Comment by ethernetdan** [comment]
Reproduced against a pull from today (kubernetes/kubernetes@1e680c9). I'm looking into whether this is intended behavior or a Kubernetes bug.

The related Kube API Server error message is produced in [/pkg/apiserver/resthandler.go:137](https://github.com/kubernetes/kubernetes/blob/1e680c9/pkg/apiserver/resthandler.go#L137)

**Comment by ethernetdan** [comment]
Here is the API call that is happening:
`curl -v "localhost:9000/api/v1/namespaces/default/services/mattermost-app?export=1"`
### Request
```
GET /api/v1/namespaces/default/services/mattermost-app?export=1 HTTP/1.1
Host: localhost:9000
User-Agent: curl/7.43.0
Accept: */*
```
### Response
**Headers**
```
HTTP/1.1 400 Bad Request
Content-Type: application/json
Date: Tue, 01 Mar 2016 00:24:43 GMT
Content-Length: 182
```
**Payload**
```json
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "export of \"services\" is not supported",
  "reason": "BadRequest",
  "code": 400
}
```

**Comment by ethernetdan** [comment]
I tested this as fixed by kubernetes/kubernetes#22285 on a recent Kube build. @kern can you confirm with the latest alpha?

**Comment by kern** [comment]
Confirmed working on the latest Kube alpha. :)

**Comment by iliocatallo** [comment]
I'm experiencing the same issue with Kubernetes 1.2.0. `kubectl version` reads:

```
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.4+3eed1e3", GitCommit:"3eed1e3be6848b877ff80a93da3785d9034d0a4f", GitTreeState:"not a git tree"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0", GitCommit:"cffae0523cfa80ddf917aba69f08508b91f603d5", GitTreeState:"clean"}
```
