### ISSUE TITLE
Slack inviter

### ISSUE THREAD

**Issue by tekacs** [redspread/spread#93]
You have a link to [Slack](http://redspread.slack.com/) in your repo, but no Slack inviter.

I understand if the intention is for it to be organisation-private, but then maybe there shouldn't be a link (or perhaps a [Gitter](http://gitter.im/) or Mattermost room for chat with the community?).

If the intention is for it to be public, then you might want to link to a Slack inviter instead, so people can join the chat. :)

(Beautiful project, by the way! :) )

**Comment by mfburnett** [comment]
Hey @tekacs - thank you for bringing this up! I just updated it with #94. Try it out. :)

(And thank you!!)
